### ISSUE TITLE
Build errors on 10 and 11i386

### ISSUE THREAD

**Issue by Jehops** [ctuffli/smart#2]
10: http://pkg.awarnach.mathstat.dal.ca/data/10i386-default/2017-10-30_08h44m48s/logs/errors/smart-0.0.4.log

11i386: http://pkg.awarnach.mathstat.dal.ca/data/11i386-default/2017-10-30_08h44m48s/logs/errors/smart-0.0.4.log

**Comment by ctuffli** [comment]
10.x is problematic because it is missing NVMe suppport as well as the `scsi_ata_pass()` interface for ATA devices attached to a SAS adapter. I can "ifdef" out unsupported code, but this starts getting messy and looses more functionality than I'd like. Any sense of how important this is for 10?

**Comment by Jehops** [comment]
My sense is that it's not worth messing up clean code for 10, which should be EOL within a year.  I asked @allanjude, who requested the port, to share his thoughts.  Is the 11i386 issue similarly problematic or is there a simpler solution I should wait for before committing the port?

**Comment by ctuffli** [comment]
No, the 11i386 fix was easy and is now committed. If 10.x isn't needed, I'll bump the revision and tag.

**Comment by Jehops** [comment]
Sounds good.  After you tag the new release I'll commit the port.  Thanks.

**Comment by Jehops** [comment]
I still see [the build error with 0.05 on 11i386](http://pkg.awarnach.mathstat.dal.ca/data/11i386-default/2017-10-31_14h39m02s/logs/errors/smart-0.0.5.log).

**Comment by ctuffli** [comment]
Hmmm, I don't see the `incomplete type` error:
```
# uname -a
FreeBSD  11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 04:10:47 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  i386
# git status
HEAD detached at 0.0.5
nothing to commit, working tree clean
# make
echo smart.full: /usr/lib/libc.a  >> .depend
Warning: Object directory not changed from original /usr/home/ctuffli/dev/smart.git
cc -O2 -pipe   -g -MD  -MF.depend.smart.o -MTsmart.o -std=gnu99 -fstack-protector-strong    -Qunused-arguments  -c smart.c -o smart.o
cc -O2 -pipe   -g -MD  -MF.depend.libsmart.o -MTlibsmart.o -std=gnu99 -fstack-protector-strong    -Qunused-arguments  -c libsmart.c -o libsmart.o
cc -O2 -pipe   -g -MD  -MF.depend.freebsd_dev.o -MTfreebsd_dev.o -std=gnu99 -fstack-protector-strong    -Qunused-arguments  -c freebsd_dev.c -o freebsd_dev.o
cc -O2 -pipe -g -std=gnu99 -fstack-protector-strong -Qunused-arguments  -o smart.full smart.o libsmart.o freebsd_dev.o  -lcam
objcopy --only-keep-debug smart.full smart.debug
objcopy --strip-debug --add-gnu-debuglink=smart.debug  smart.full smart
# 
```
OK, it looks like `struct scsi_log_informational_exceptions` wasn't introduced until 11.1

**Comment by ctuffli** [comment]
This should build cleanly with >= 11.0 now

**Comment by Jehops** [comment]
Confirmed.  Thanks.

**Comment by Jehops** [comment]
P.S., the port is in the tree. :)  http://www.freshports.org/sysutils/smart/

**Comment by ctuffli** [comment]
@jehops Thanks for getting that done!
