### ISSUE TITLE
Missing manual page for smart command

### ISSUE THREAD

**Issue by cemeyer** [ctuffli/smart#4]
It'd be good to provide and install a manual page documenting the options to the `smart` command.

**Comment by ctuffli** [comment]
Yup, fair request. I haven't really done a man page before so let me see if I can coax (trick?) one of the instigators of this code into making one. Failing that, "how hard could it be?"

**Comment by cemeyer** [comment]
It's pretty easy!  I'd suggest starting from an example page from a similar type of program and then referencing the mdoc(7) page, which provides a high-level overview of typical sections and goes into the nitty gritty formatting details, as needed.

**Comment by ctuffli** [comment]
After an embarrassingly long time, fixed with 87b9b30da24925ac220f25825fa66d22cb85dc42

**Comment by cemeyer** [comment]
Thanks!
